name: DevOps GitHub Action Demo

on: push

jobs:
  demo:
      name: GitHub actions Demo
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Check the file
          run: ls -lrt

