name: DevOps GitHub Action Demo

on: push

jobs:
  demo:
      name: GitHub actions Demo
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - uses: actions/checkout@v3
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'adopt'
        